'use client';

import { useEffect, useState } from 'react';
import { useRouter, useSearchParams } from 'next/navigation';
import { useAuth } from '../../contexts/AuthContext';
import { supabase } from '../../lib/supabase';
import { ReportData } from '../../types/parent/insightsReportTypes';
import { formatReportDate } from '../../utils/reportUtils';
import AppIcon from '../../components/ui/AppIcon';
import {
  PrintStyles,
  ReportActionBar,
  ReportHeader,
  ExecutiveSummary,
  ProgressTimeline,
  SubjectAnalysisTable,
  StrengthsList,
  AreasForSupportList,
  RecentSessionsTable,
  ConversationStarters,
} from '../../components/parent/report';

export default function InsightsReport() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const { user, isParent, loading: authLoading } = useAuth();

  const [reportData, setReportData] = useState<ReportData | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const childId = searchParams.get('childId');

  useEffect(() => {
    if (authLoading) return;
    if (!user) {
      router.replace('/');
    } else if (!isParent) {
      router.replace('/child/today');
    }
  }, [authLoading, user, isParent, router]);

  useEffect(() => {
    if (!childId || !user) return;

    async function fetchReportData() {
      setLoading(true);
      setError(null);

      try {
        const { data, error: rpcError } = await supabase.rpc('rpc_get_report_data', {
          p_child_id: childId,
        });

        if (rpcError) throw rpcError;
        setReportData(data);
      } catch (err: any) {
        console.error('Error fetching report data:', err);
        setError(err.message);
      } finally {
        setLoading(false);
      }
    }

    fetchReportData();
  }, [childId, user]);

  const handlePrint = () => {
    window.print();
  };

  const handleBack = () => {
    router.push('/parent/insights');
  };

  if (authLoading || loading) {
    return (
      <div className="min-h-screen bg-white flex items-center justify-center">
        <div className="text-center">
          <AppIcon
            name="loader"
            className="text-indigo-600 text-2xl animate-spin mb-3"
          />
          <p className="text-sm text-gray-600">Generating report...</p>
        </div>
      </div>
    );
  }

  if (error || !reportData) {
    return (
      <div className="min-h-screen bg-white flex items-center justify-center">
        <div className="text-center">
          <p className="text-red-600 mb-4">{error || 'Failed to load report data'}</p>
          <button onClick={handleBack} className="text-indigo-600 hover:underline">
            ← Back to Insights
          </button>
        </div>
      </div>
    );
  }

  return (
    <>
      <PrintStyles />
      <ReportActionBar onBack={handleBack} onPrint={handlePrint} />

      <div className="print-container bg-white min-h-screen">
        <div className="px-8 py-10">
          <ReportHeader
            childName={reportData.child_name}
            generatedAt={reportData.generated_at}
            reportDate={reportData.report_date}
          />

          <ExecutiveSummary lifetime={reportData.lifetime} streak={reportData.streak} />

          <ProgressTimeline
            thisWeek={reportData.this_week}
            thisMonth={reportData.this_month}
            lifetime={reportData.lifetime}
          />

          <SubjectAnalysisTable subjects={reportData.subjects} />

          <StrengthsList strengths={reportData.strengths} />

          <AreasForSupportList areasForSupport={reportData.areas_for_support} />

          <RecentSessionsTable recentSessions={reportData.recent_sessions} />

          <ConversationStarters
            childName={reportData.child_name}
            lifetimeSessions={reportData.lifetime.total_sessions}
            currentStreak={reportData.streak.current}
            strengths={reportData.strengths}
            areasForSupport={reportData.areas_for_support}
          />

          <footer className="border-t border-gray-200 pt-6 mt-10 text-center text-sm text-gray-500">
            <p>Generated by Doorslam • {formatReportDate(reportData.generated_at)}</p>
            <p className="mt-1">
              This report is based on self-reported confidence levels during revision sessions.
            </p>
          </footer>
        </div>
      </div>
    </>
  );
}
